# Generated by Django 3.2.3 on 2021-05-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Won', models.BooleanField(default=False)),
                ('Lost', models.BooleanField(default=False)),
            ],
        ),
    ]
