# Generated by Django 3.2.3 on 2021-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Won',
            field=models.IntegerField(default=0),
        ),
    ]
